{"uuid": "88b623b9-c090-4c33-820e-e4f2e9963147", "children": ["1569a9ab-271e-4231-bf3f-6b289e506295"], "befores": [{"name": "driver", "status": "passed", "start": 1742894836366, "stop": 1742894837553}], "afters": [{"name": "driver::0", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"D:\\Python39\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"E:\\AutoTest\\FgAI\\conftest.py\", line 68, in driver\n    DriverManager.quit_driver()\n  File \"E:\\AutoTest\\FgAI\\common\\driver_manager.py\", line 48, in quit_driver\n    cls._driver.quit()\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 193, in quit\n    self.service.stop()\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 157, in stop\n    self.send_remote_shutdown_command()\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 142, in send_remote_shutdown_command\n    if not self.is_connectable():\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 131, in is_connectable\n    return utils.is_connectable(self.port)\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\common\\utils.py\", line 101, in is_connectable\n    socket_ = socket.create_connection((host, port), 1)\n  File \"D:\\Python39\\lib\\socket.py\", line 831, in create_connection\n    sock.connect(sa)\n"}, "start": 1742894842989, "stop": 1742894845030}], "start": 1742894836366, "stop": 1742894845030}