INFO     automation:test_CaseMg.py:84 ========== 开始执行测试: test_case_crud ==========
WARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 Exception managing chrome: error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json)
WARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (113.0.5672.63) detected in PATH at D:\Python39\chromedriver.exe might not be compatible with the detected chrome version (135.0.7049.85); currently, chromedriver  is recommended for chrome 135.*, so it is advised to delete the driver in PATH and retry
WARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event)