{"uuid": "7b28d504-e349-4cab-b523-5c1ed0885390", "children": ["44ba20e9-d122-44d7-b8c7-2f2982a4cb5b"], "befores": [{"name": "init_driver", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestDossierUpload' object has no attribute 'driver'\n", "trace": "  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"E:\\AutoTest\\FgAI\\test_001\\test_DossierU.py\", line 56, in init_driver\n    self.driver.get_screenshot_as_png(),\n"}, "start": 1742904485270, "stop": 1742904485271}], "start": 1742904485270, "stop": 1742904485279}